# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2fa7a0fcb0f5f3f0bf5478c3c4c401128fb1358d9bef6a044e6919c848738a969acd263e6b479000809092362f84911c44b3b2b4ed522e800f1dd576b7e9670a

test:
  secret_key_base: 4eb268fab71122a1b52eb442f2fc39f07ac36e2bb7f0d6a49f8212bc17cbfe11350af9c551f367eea59d9cc3c0757ebb5048e7e3b9924798e01d6b01201542f7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
